"""replace storage_path with cloud_url

Revision ID: 9707995f176b
Revises: 5f2759f34848
Create Date: 2026-06-28 00:52:49.807782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9707995f176b'
down_revision: Union[str, Sequence[str], None] = '5f2759f34848'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('papers', sa.Column('cloud_url', sa.Text(), nullable=True))
    op.drop_column('papers', 'storage_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('papers', sa.Column('storage_path', sa.TEXT(), nullable=False))
    op.drop_column('papers', 'cloud_url')
    # ### end Alembic commands ###
