from pydantic import BaseModel, Field
from typing import List

class ResearchReport(BaseModel):
    """
    The final human-readable research report generated by the LLM layer.
    """
    executive_summary: str = Field(description="High-level overview of the findings")
    method_comparison: str = Field(description="Narrative comparison of different methodologies")
    trend_analysis: str = Field(description="Analysis of trends over time across the research context")
    research_gaps: str = Field(description="Detailed analysis of the detected contradictions and gaps")
    innovation_opportunities: str = Field(description="Novel opportunities or proposals for future research")
    references: List[str] = Field(description="List of cited references and sources")
